### ISSUE TITLE
Add a subsection in `Program Lifting`, to list binary lifters/ILs

### ISSUE THREAD

**Issue by mahaloz** [mahaloz/decompilation-wiki#13]
Start with the list: https://docs.google.com/spreadsheets/d/1XPTe5sj1Vx9O40HuKLadU-pwit91Hzk_YdrV8wcFllQ/edit#gid=0

Given by @psifertex

**Comment by cascades-sjtu** [comment]
I would recommend this slide (page 33) for broadening the list: https://binary.ninja/presentations/Modern%20Binary%20Analysis%20with%20ILs%20with%20notes.pdf

The video is here: https://www.youtube.com/watch?v=Q-FWpakkBFw

**Comment by psifertex** [comment]
That slide and talk are actually older versions of the same spreadsheet linked above. Glad to see people know if it at least though. :-)

**Comment by cascades-sjtu** [comment]
Thanks! That slide was included in my master thesis's references and helped me a lot. I may update the references related to lifting.
